/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.materials;

import controllers.MaterialsController;
import java.awt.Color;
import javax.swing.JOptionPane;
import sources.Material;
import views.main.ApplicationView;

/**
 *
 * @author nyko-
 */
public class New extends javax.swing.JInternalFrame {

    /**
     * Creates new form New
     */
    public New() {
        initComponents();
        initFields();
    }

    private void initFields() {
        this.rb_active.setSelected(true);
        this.btn_cancel.setForeground(Color.RED);
    }

    private Material buildMaterial() {
        String name = tf_name.getText();
        boolean active = rb_active.isSelected();

        return new Material(name, active);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_back = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();
        lbl_or = new javax.swing.JLabel();
        rowPane = new javax.swing.JPanel();
        col1Pane = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        col2Pane = new javax.swing.JPanel();
        lbl_status = new javax.swing.JLabel();
        rb_active = new javax.swing.JRadioButton();
        rb_inactive = new javax.swing.JRadioButton();
        btn_cancel = new javax.swing.JButton();

        btn_back.setText("Voltar");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_submit.setText("Adicionar");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        lbl_or.setText("ou");

        lbl_name.setText("* Nome:");

        javax.swing.GroupLayout col1PaneLayout = new javax.swing.GroupLayout(col1Pane);
        col1Pane.setLayout(col1PaneLayout);
        col1PaneLayout.setHorizontalGroup(
            col1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(col1PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(col1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(col1PaneLayout.createSequentialGroup()
                        .addComponent(lbl_name)
                        .addGap(0, 227, Short.MAX_VALUE))
                    .addComponent(tf_name))
                .addContainerGap())
        );
        col1PaneLayout.setVerticalGroup(
            col1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(col1PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        lbl_status.setText("Situação:");

        rb_active.setText("Ativo");
        rb_active.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_activeActionPerformed(evt);
            }
        });

        rb_inactive.setText("Inativo");
        rb_inactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_inactiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout col2PaneLayout = new javax.swing.GroupLayout(col2Pane);
        col2Pane.setLayout(col2PaneLayout);
        col2PaneLayout.setHorizontalGroup(
            col2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(col2PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(col2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(col2PaneLayout.createSequentialGroup()
                        .addComponent(rb_active)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_inactive))
                    .addComponent(lbl_status))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        col2PaneLayout.setVerticalGroup(
            col2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(col2PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(col2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_active)
                    .addComponent(rb_inactive))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rowPaneLayout = new javax.swing.GroupLayout(rowPane);
        rowPane.setLayout(rowPaneLayout);
        rowPaneLayout.setHorizontalGroup(
            rowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rowPaneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(col1Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(col2Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rowPaneLayout.setVerticalGroup(
            rowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rowPaneLayout.createSequentialGroup()
                .addGroup(rowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(col1Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(col2Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btn_cancel.setText("Cancelar");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_back))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_submit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_or)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cancel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(rowPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rowPane, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_or)
                    .addComponent(btn_submit)
                    .addComponent(btn_cancel))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        List frame = new List();
        ApplicationView.changeInternalFrame(frame);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        Material newMaterial = buildMaterial();
        String errors = new MaterialsController().create(newMaterial);

        if (errors == null || errors.isEmpty()) {
            List frame = new List();
            ApplicationView.changeInternalFrame(frame);
        } else {
            JOptionPane.showMessageDialog(null, errors);
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void rb_activeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_activeActionPerformed
        rb_active.setSelected(true);
        rb_inactive.setSelected(false);
    }//GEN-LAST:event_rb_activeActionPerformed

    private void rb_inactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_inactiveActionPerformed
        rb_active.setSelected(false);
        rb_inactive.setSelected(true);
    }//GEN-LAST:event_rb_inactiveActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        List frame = new List();
        ApplicationView.changeInternalFrame(frame);
    }//GEN-LAST:event_btn_cancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_submit;
    private javax.swing.JPanel col1Pane;
    private javax.swing.JPanel col2Pane;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_or;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JRadioButton rb_active;
    private javax.swing.JRadioButton rb_inactive;
    private javax.swing.JPanel rowPane;
    private javax.swing.JTextField tf_name;
    // End of variables declaration//GEN-END:variables
}
