/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.main;

import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author nyko-
 */
public class ApplicationView extends javax.swing.JFrame {

    private static ApplicationView applicationView;

    /**
     * Creates new form MainView
     */
    public ApplicationView() {
        initComponents();

        this.applicationView = this;
    }

    public static void changeInternalFrame(Object object) {
        JInternalFrame frame = (JInternalFrame) object;
        frame.setBorder(null);

        BasicInternalFrameUI bi = (BasicInternalFrameUI) frame.getUI();
        bi.setNorthPane(null);

        applicationView.desktopPane.removeAll();
        applicationView.desktopPane.add(frame);
        frame.setVisible(true);

        // setMaximum works only after setVisible
        try {
            frame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            System.out.println("Erro ao maximizar tela " + frame.getName() + ": " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        welcome = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        registerMenu = new javax.swing.JMenu();
        categoryMenuItem = new javax.swing.JMenuItem();
        materialMenuItem = new javax.swing.JMenuItem();
        userMenuItem = new javax.swing.JMenuItem();
        calculatorMenu = new javax.swing.JMenu();
        calculatorMenuItem = new javax.swing.JMenuItem();
        auditMenu = new javax.swing.JMenu();
        auditMenuItem = new javax.swing.JMenuItem();
        optionMenu = new javax.swing.JMenu();
        optionMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arquitetando");

        desktopPane.setBackground(new java.awt.Color(240, 240, 240));

        welcome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        welcome.setText("Bem Vindo");

        desktopPane.setLayer(welcome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(welcome)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(welcome)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        registerMenu.setText("Cadastros");

        categoryMenuItem.setText("Categorias");
        categoryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryMenuItemActionPerformed(evt);
            }
        });
        registerMenu.add(categoryMenuItem);

        materialMenuItem.setText("Materiais");
        materialMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialMenuItemActionPerformed(evt);
            }
        });
        registerMenu.add(materialMenuItem);

        userMenuItem.setText("Usuários");
        userMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMenuItemActionPerformed(evt);
            }
        });
        registerMenu.add(userMenuItem);

        menuBar.add(registerMenu);

        calculatorMenu.setText("Calculo");

        calculatorMenuItem.setText("Calcular Transmitância Térmica");
        calculatorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorMenuItemActionPerformed(evt);
            }
        });
        calculatorMenu.add(calculatorMenuItem);

        menuBar.add(calculatorMenu);

        auditMenu.setText("Auditoria");

        auditMenuItem.setText("Listagem");
        auditMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auditMenuItemActionPerformed(evt);
            }
        });
        auditMenu.add(auditMenuItem);

        menuBar.add(auditMenu);

        optionMenu.setText("Configurações");

        optionMenuItem.setText("Configurações");
        optionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionMenuItemActionPerformed(evt);
            }
        });
        optionMenu.add(optionMenuItem);

        menuBar.add(optionMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void materialMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialMenuItemActionPerformed
        views.materials.List frame = new views.materials.List();
        changeInternalFrame(frame);
    }//GEN-LAST:event_materialMenuItemActionPerformed

    private void categoryMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryMenuItemActionPerformed
        views.categories.List frame = new views.categories.List();
        changeInternalFrame(frame);
    }//GEN-LAST:event_categoryMenuItemActionPerformed

    private void optionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionMenuItemActionPerformed
        views.options.Config frame = new views.options.Config();
        changeInternalFrame(frame);
    }//GEN-LAST:event_optionMenuItemActionPerformed

    private void auditMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auditMenuItemActionPerformed
        views.audits.List frame = new views.audits.List();
        changeInternalFrame(frame);
    }//GEN-LAST:event_auditMenuItemActionPerformed

    private void calculatorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorMenuItemActionPerformed
        views.thermalTransmittance.Calculate frame = new views.thermalTransmittance.Calculate();
        changeInternalFrame(frame);
    }//GEN-LAST:event_calculatorMenuItemActionPerformed

    private void userMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMenuItemActionPerformed
        views.users.List frame = new views.users.List();
        changeInternalFrame(frame);
    }//GEN-LAST:event_userMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ApplicationView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu auditMenu;
    private javax.swing.JMenuItem auditMenuItem;
    private javax.swing.JMenu calculatorMenu;
    private javax.swing.JMenuItem calculatorMenuItem;
    private javax.swing.JMenuItem categoryMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem materialMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu optionMenu;
    private javax.swing.JMenuItem optionMenuItem;
    private javax.swing.JMenu registerMenu;
    private javax.swing.JMenuItem userMenuItem;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
