/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.categories;

import forms.CategoryForm;
import java.awt.Color;

/**
 *
 * @author nyko-
 */
public class Form extends javax.swing.JInternalFrame {

    private final CategoryForm form;

    /**
     * Creates new form Form
     *
     * @param id
     */
    public Form(int id) {
        form = new CategoryForm(id);

        initComponents();
        initFields();
    }

    /**
     * Creates new form FormView
     */
    public Form() {
        form = new CategoryForm();

        initComponents();
        initFields();
    }

    private void initFields() {
        this.nameTextField.setText(form.getName());
        this.inactiveRadioButton.setSelected(form.isInactive());
        this.activeRadioButton.setSelected(form.isActive());
        this.cancellButton.setForeground(Color.RED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the CategoryForm Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        orLabel = new javax.swing.JLabel();
        rowPane = new javax.swing.JPanel();
        col1Pane = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        col2Pane = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        activeRadioButton = new javax.swing.JRadioButton();
        inactiveRadioButton = new javax.swing.JRadioButton();
        cancellButton = new javax.swing.JButton();

        backButton.setText("Voltar");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Gravar");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        orLabel.setText("ou");

        nameLabel.setText("* Nome:");

        javax.swing.GroupLayout col1PaneLayout = new javax.swing.GroupLayout(col1Pane);
        col1Pane.setLayout(col1PaneLayout);
        col1PaneLayout.setHorizontalGroup(
            col1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(col1PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(col1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(col1PaneLayout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(0, 227, Short.MAX_VALUE))
                    .addComponent(nameTextField))
                .addContainerGap())
        );
        col1PaneLayout.setVerticalGroup(
            col1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(col1PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        statusLabel.setText("Situação:");

        activeRadioButton.setText("Ativo");
        activeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeRadioButtonActionPerformed(evt);
            }
        });

        inactiveRadioButton.setText("Inativo");
        inactiveRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inactiveRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout col2PaneLayout = new javax.swing.GroupLayout(col2Pane);
        col2Pane.setLayout(col2PaneLayout);
        col2PaneLayout.setHorizontalGroup(
            col2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(col2PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(col2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(col2PaneLayout.createSequentialGroup()
                        .addComponent(activeRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inactiveRadioButton))
                    .addComponent(statusLabel))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        col2PaneLayout.setVerticalGroup(
            col2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(col2PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(col2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activeRadioButton)
                    .addComponent(inactiveRadioButton))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rowPaneLayout = new javax.swing.GroupLayout(rowPane);
        rowPane.setLayout(rowPaneLayout);
        rowPaneLayout.setHorizontalGroup(
            rowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rowPaneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(col1Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(col2Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rowPaneLayout.setVerticalGroup(
            rowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rowPaneLayout.createSequentialGroup()
                .addGroup(rowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(col1Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(col2Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        cancellButton.setText("Cancelar");
        cancellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancellButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(orLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancellButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(rowPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rowPane, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orLabel)
                    .addComponent(submitButton)
                    .addComponent(cancellButton))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        form.cancel();
    }//GEN-LAST:event_backButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String name = nameTextField.getText();
        boolean active = activeRadioButton.isSelected();

        form.save(name, active);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void activeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeRadioButtonActionPerformed
        activeRadioButton.setSelected(true);
        inactiveRadioButton.setSelected(false);
    }//GEN-LAST:event_activeRadioButtonActionPerformed

    private void inactiveRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inactiveRadioButtonActionPerformed
        activeRadioButton.setSelected(false);
        inactiveRadioButton.setSelected(true);
    }//GEN-LAST:event_inactiveRadioButtonActionPerformed

    private void cancellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancellButtonActionPerformed
        form.cancel();
    }//GEN-LAST:event_cancellButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activeRadioButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton cancellButton;
    private javax.swing.JPanel col1Pane;
    private javax.swing.JPanel col2Pane;
    private javax.swing.JRadioButton inactiveRadioButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel orLabel;
    private javax.swing.JPanel rowPane;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
