/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.thermalTransmittance;

import java.util.ArrayList;
import javafx.collections.FXCollections;
import javafx.collections.ListChangeListener;
import javafx.collections.ObservableList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nyko-
 */
public class Calculate extends javax.swing.JInternalFrame {

    private ObservableList<Item> items;

    /**
     * Creates new form List
     */
    public Calculate() {
        initComponents();

        items = FXCollections.observableList(new ArrayList<>());

        items.addListener((ListChangeListener.Change<? extends Item> c) -> {
            c.next();
            setTableData(tableData(items.toArray()), tableHeader());
        });

        setTableData(tableData(items.toArray()), tableHeader());
    }

    private void setTableData(Object[][] tableData, String[] tableHeader) {
        table.setModel(new DefaultTableModel(tableData, tableHeader) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // coluna não editavel
                return false;
            }
        });

        setTableConfig();
    }

    private String[] tableHeader() {
        String[] header = {
            "Material",
            "Indice de Condutividade Termica",
            "Largura (m)",
            "Resistência térmica",
            "",
            ""
        };

        return header;
    }

    private Object[][] tableData(Object[] items) {
        int row = 0;
        Object[][] data = new Object[items.length][6];

        for (Object object : items) {
            Item item = (Item) object;

            data[row][0] = item.getMaterial().getName();
            data[row][1] = item.getMaterial().getThermalConductivityIndex();
            data[row][2] = item.getWidth();
            data[row][3] = item.getThermalConductivity();

            data[row][4] = new ImageIcon(getClass().getResource("/images/pencil.png"));
            data[row][5] = new ImageIcon(getClass().getResource("/images/times.png"));

            row++;
        }

        return data;
    }

    private void setTableConfig() {
        // não redimencionavel
        table.getTableHeader().setReorderingAllowed(false);

        // não selecionar linha
        table.setRowSelectionAllowed(false);

        // definir conteudo como img
        table.getColumnModel().getColumn(4).setCellRenderer(table.getDefaultRenderer(ImageIcon.class));
        table.getColumnModel().getColumn(5).setCellRenderer(table.getDefaultRenderer(ImageIcon.class));

        setTableColumnsWidth();
        setTableColumnAction();
    }

    private void setTableColumnsWidth() {
        table.getColumnModel().getColumn(4).setWidth(20);
        table.getColumnModel().getColumn(4).setMinWidth(20);
        table.getColumnModel().getColumn(4).setMaxWidth(20);

        table.getColumnModel().getColumn(5).setWidth(20);
        table.getColumnModel().getColumn(5).setMinWidth(20);
        table.getColumnModel().getColumn(5).setMaxWidth(20);
    }

    private void setTableColumnAction() {
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = table.rowAtPoint(evt.getPoint());
                int col = table.columnAtPoint(evt.getPoint());

                if (row >= 0 && col == 4) {
                    Item item = items.get(row);
                    new ItemModal().edit(item);
                    items.set(row, item);
                } else if (row >= 0 && col == 5) {
                    items.remove(row);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_new = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        btn_new.setText("Adicionar");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_new)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_new)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        Item item = new Item();
        new ItemModal().add(item);

        if (item.getMaterial() != null && item.getWidth() > 0) {
            items.add(item);
        }

        //definirPainel();
        //popularTabela(tableData(), tableHeader());
        //cofigurarTabela();
    }//GEN-LAST:event_btn_newActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_new;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
