version: '3'

volumes:
  db:

services:
  api:
    container_name: api
    restart: always
    build: .
    working_dir: /server-api
    volumes:
      - ./server-api:/server-api
    expose:
      - "8080"
    ports:
      - 8080:8080
    command: mvn spring-boot:run # mvn clean spring-boot:run
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:9.6
    container_name: "db"
    environment:
      - POSTGRES_DB=projeto_integrador
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
